name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Alterar para o branch que deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Você pode especificar a versão do Node.js que sua aplicação usa

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build
    - name: Uninstall deprecated AWS CLI npm package
      run: npm uninstall -g aws-cli
    - name: Install AWS CLI using pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli

    - name: Deploy to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        npm install -g aws-cli
        aws s3 sync build/ s3://$AWS_BUCKET_NAME --region $AWS_REGION --delete --acl public-read

