name: Build and Deploy
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
permissions:
  contents: write
  pages: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build
          
      - name: Render Deploy Action
        uses: johnbeynon/render-deploy-action@v0.0.8
        
     # - name: Deploy 🚀
      #  uses: JamesIves/github-pages-deploy-action@v4
      #  with:
      #    folder: build # The folder the action should deploy.
      #    branch: gh-pages
       #   token: ${{ secrets.GITHUB_TOKEN }}  # Usar o token de acesso para autenticação
              
            
